# Generated by Django 6.1 on 2026-09-03 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='key name')),
                ('key_prefix', models.CharField(max_length=10, verbose_name='key prefix')),
                ('key_hash', models.CharField(db_index=True, max_length=128, verbose_name='key hash')),
                ('scope', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read and Write'), ('admin', 'Full Access')], default='read', max_length=10, verbose_name='scope')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'key_hash'], name='api_keys_project_515885_idx'), models.Index(fields=['is_active', 'expires_at'], name='api_keys_is_acti_f90a04_idx')],
            },
        ),
    ]
