# Generated by Django 6.1 on 2026-09-03 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0001_initial'),
        ('gateway', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], db_index=True, max_length=10, verbose_name='metric type')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='period start')),
                ('period_end', models.DateTimeField(db_index=True, verbose_name='period end')),
                ('total_requests', models.IntegerField(default=0, verbose_name='total requests')),
                ('successful_requests', models.IntegerField(default=0, verbose_name='successful requests')),
                ('failed_requests', models.IntegerField(default=0, verbose_name='failed requests')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='average response time')),
                ('min_response_time', models.IntegerField(default=0, verbose_name='minimum response time')),
                ('max_response_time', models.IntegerField(default=0, verbose_name='maximum response time')),
                ('status_code_distribution', models.JSONField(default=dict, verbose_name='status code distribution')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('api_definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='gateway.apidefinition', verbose_name='API definition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'aggregated metric',
                'verbose_name_plural': 'aggregated metrics',
                'db_table': 'aggregated_metrics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['project', 'metric_type', 'period_start'], name='aggregated__project_8dba31_idx'), models.Index(fields=['api_definition', 'period_start'], name='aggregated__api_def_87cd3d_idx')],
                'unique_together': {('project', 'api_definition', 'metric_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP method')),
                ('path', models.CharField(max_length=500, verbose_name='endpoint path')),
                ('full_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='full URL')),
                ('status_code', models.IntegerField(db_index=True, verbose_name='status code')),
                ('response_time', models.IntegerField(db_index=True, verbose_name='response time (ms)')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user agent')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='request body')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='response body')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('is_error', models.BooleanField(db_index=True, default=False, verbose_name='is error')),
                ('is_authenticated', models.BooleanField(default=True, verbose_name='is authenticated')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('api_definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='gateway.apidefinition', verbose_name='API definition')),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api_keys.apikey', verbose_name='API Key')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'request log',
                'verbose_name_plural': 'request logs',
                'db_table': 'request_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='request_log_project_517bd7_idx'), models.Index(fields=['api_key', 'created_at'], name='request_log_api_key_f45bc5_idx'), models.Index(fields=['status_code', 'created_at'], name='request_log_status__65f266_idx'), models.Index(fields=['project', 'api_definition', 'created_at'], name='request_log_project_474e07_idx')],
            },
        ),
    ]
