# Generated by Django 6.1 on 2026-09-03 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'API category',
                'verbose_name_plural': 'API categories',
                'db_table': 'api_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='API name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('path', models.CharField(max_length=255, verbose_name='endpoint path')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='HTTP method')),
                ('requires_auth', models.BooleanField(default=True, verbose_name='requires authentication')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('default_rate_limit', models.IntegerField(default=100, verbose_name='default rate limit per hour')),
                ('response_schema', models.JSONField(blank=True, help_text='JSON schema for the response', null=True, verbose_name='response schema')),
                ('mock_data', models.JSONField(blank=True, help_text='Mock data to return for this endpoint', null=True, verbose_name='mock data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='gateway.apicategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'API definition',
                'verbose_name_plural': 'API definitions',
                'db_table': 'api_definitions',
                'ordering': ['category', 'name'],
                'unique_together': {('path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAPIAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_limit', models.IntegerField(blank=True, help_text='Override the default rate limit for this API', null=True, verbose_name='rate limit per hour')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('enabled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enabled at')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='disabled at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('api_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='gateway.apidefinition', verbose_name='API definition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_apis', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'project API assignment',
                'verbose_name_plural': 'project API assignments',
                'db_table': 'project_api_assignments',
                'indexes': [models.Index(fields=['project', 'is_enabled'], name='project_api_project_f63cfa_idx')],
                'unique_together': {('project', 'api_definition')},
            },
        ),
    ]
